In [198]:
import pandas as pd
df_transactions = pd.read_parquet('ledger_transactions.parquet')

df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     5000 non-null   str
 1   applicant_id       5000 non-null   str
 2   timestamp          5000 non-null   datetime64[us]
 3   amount             5000 non-null   float64
 4   terminal_location  5000 non-null   str
 5   category           5000 non-null   str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 401.9 KB

In [ ]:
import pandas as pd
df_transactions = pd.read_parquet('ledger_transactions.parquet')

mean_amount = df_transactions.groupby("category")["amount"].transform("mean")
std_amount = df_transactions.groupby("category")["amount"].transform("std")

upper_limit = mean_amount + (3 * std_amount)
is_outlier = df_transactions["amount"] > upper_limit
df_transactions = df_transactions[~is_outlier]

df_transactions.info()

,transaction_id,applicant_id,timestamp,amount,terminal_location,category
0,TX00000,APP004,2026-08-01 00:00:00,73.998193,Tbilisi Central,Groceries
1,TX00001,APP005,2026-08-01 00:01:00,117.054648,Kutaisi Station,Groceries
2,TX00002,APP003,2026-08-01 00:02:00,516.611718,Tbilisi Central,Retail
3,TX00003,APP005,2026-08-01 00:03:00,10.332549,Online Gateway,Travel
4,TX00004,APP005,2026-08-01 00:04:00,156.754191,Online Gateway,Retail
5,TX00005,APP002,2026-08-01 00:05:00,11.549235,Online Gateway,Utilities
6,TX00006,APP003,2026-08-01 00:06:00,70.613129,Tbilisi Central,Retail
7,TX00007,APP003,2026-08-01 00:07:00,244.304230,Online Gateway,Retail
8,TX00008,APP003,2026-08-01 00:08:00,85.234378,Online Gateway,Groceries
9,TX00009,APP005,2026-08-01 00:09:00,880.778019,Kutaisi Station,Retail
10,TX00010,APP004,2026-08-01 00:10:00,122.826727,Kutaisi Station,Utilities
11,TX00011,APP003,2026-08-01 00:11:00,58.105949,Batumi Mall,Groceries
12,TX00012,APP006,2026-08-01 00:12:00,37.290614,Batumi Mall,Utilities
13,TX00013,APP005,2026-08-01 00:13:00,64.737609,Batumi Mall,Retail
14,TX00014,APP002,2026-08-01 00:14:00,69.909695,Tbilisi Central,Utilities
15,TX00015,APP004,2026-08-01 00:15:00,10.678276,Batumi Mall,Utilities
16,TX00016,APP006,2026-08-01 00:16:00,69.203972,Tbilisi Central,Retail
17,TX00017,APP006,2026-08-01 00:17:00,93.609932,Tbilisi Central,Retail
18,TX00018,APP002,2026-08-01 00:18:00,192.418722,Batumi Mall,Groceries
19,TX00019,APP004,2026-08-01 00:19:00,160.385470,Batumi Mall,Groceries
20,TX00020,APP005,2026-08-01 00:20:00,185.044054,Tbilisi Central,Travel
21,TX00021,APP001,2026-08-01 00:21:00,1.259828,Kutaisi Station,Groceries
22,TX00022,APP004,2026-08-01 00:22:00,36.821296,Online Gateway,Retail
23,TX00023,APP002,2026-08-01 00:23:00,162.566364,Online Gateway,Utilities
24,TX00024,APP006,2026-08-01 00:24:00,99.244186,Online Gateway,Utilities
25,TX00025,APP005,2026-08-01 00:25:00,0.799146,Kutaisi Station,Groceries
26,TX00026,APP004,2026-08-01 00:26:00,244.825124,Tbilisi Central,Groceries
27,TX00027,APP001,2026-08-01 00:27:00,222.295009,Batumi Mall,Retail
28,TX00028,APP001,2026-08-01 00:28:00,119.250132,Tbilisi Central,Utilities
29,TX00029,APP003,2026-08-01 00:29:00,10.316254,Tbilisi Central,Travel
30,TX00030,APP003,2026-08-01 00:30:00,218.195648,Batumi Mall,Travel
31,TX00031,APP002,2026-08-01 00:31:00,131.457265,Kutaisi Station,Groceries
32,TX00032,APP004,2026-08-01 00:32:00,228.461496,Online Gateway,Travel
33,TX00033,APP004,2026-08-01 00:33:00,208.996029,Online Gateway,Retail
34,TX00034,APP006,2026-08-01 00:34:00,243.684310,Tbilisi Central,Travel
35,TX00035,APP006,2026-08-01 00:35:00,109.474185,Kutaisi Station,Groceries
36,TX00036,APP006,2026-08-01 00:36:00,22.680046,Online Gateway,Retail
37,TX00037,APP003,2026-08-01 00:37:00,166.826443,Kutaisi Station,Utilities
38,TX00038,APP004,2026-08-01 00:38:00,145.324741,Batumi Mall,Retail
39,TX00039,APP004,2026-08-01 00:39:00,203.366628,Tbilisi Central,Groceries
40,TX00040,APP001,2026-08-01 00:40:00,27.927933,Tbilisi Central,Groceries
41,TX00041,APP003,2026-08-01 00:41:00,32.532329,Kutaisi Station,Travel
42,TX00042,APP005,2026-08-01 00:42:00,331.650712,Online Gateway,Travel
43,TX00043,APP003,2026-08-01 00:43:00,207.930834,Kutaisi Station,Utilities
44,TX00044,APP005,2026-08-01 00:44:00,358.268005,Batumi Mall,Utilities
45,TX00045,APP001,2026-08-01 00:45:00,213.266670,Online Gateway,Groceries
46,TX00046,APP002,2026-08-01 00:46:00,136.380625,Online Gateway,Groceries
47,TX00047,APP004,2026-08-01 00:47:00,159.255032,Kutaisi Station,Groceries
48,TX00048,APP001,2026-08-01 00:48:00,329.906732,Batumi Mall,Utilities
49,TX00049,APP004,2026-08-01 00:49:00,129.699530,Online Gateway,Groceries

In [150]:
import pandas as pd
import json

# read data
df_applications = pd.read_csv('applications.csv')
with open('bureau_scores.json') as f:
    raw_bureau_scores = json.load(f)

# normalize collumn names and clean dupplicates
df_bureau_scores = pd.json_normalize(raw_bureau_scores)
df_applications.columns = df_applications.columns.str.replace(' ', '')

transformed_income = df_applications.groupby("education_level")["monthly_income"].transform('median')
filled_df_applications = df_applications.fillna({'monthly_income': transformed_income})

filled_df_applications["submission_date"]= pd.to_datetime(filled_df_applications['submission_date'], format='mixed',dayfirst=True, errors='coerce')
sorted_applications = filled_df_applications.sort_values(by='submission_date', ascending=False)
drop_duplicates_applications = sorted_applications.drop_duplicates(subset='applicant_id', keep='first')


# join two tables
clean_applications_with_scores = df_bureau_scores.set_index("applicant_id").join(drop_duplicates_applications.set_index("applicant_id"),how='inner')


clean_applications_with_scores.head(20)

,credit_profile.bureau_score,credit_profile.past_defaults,credit_profile.hard_inquiries,full_name,submission_date,monthly_income,education_level,employment_status
applicant_id,,,,,,,,
APP001,720,0,1,Giorgi Beridze,2026-03-09,2500.0,Bachelor,Employed
APP002,580,2,4,Nino Kalandadze,2026-09-29,1800.0,Master,Employed
APP003,640,1,2,Levan Jishkariani,2026-04-09,1200.0,High School,Unemployed
APP004,790,0,0,Mariam Lomidze,2026-05-09,4200.0,PhD,Employed
APP005,550,3,5,Irakli Mgeladze,2026-09-26,2500.0,Bachelor,Self-Employed
APP006,710,0,1,Salome Kankia,2026-11-16,3100.0,Master,Employed